name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Terraform Stacks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: |
        cd terraform/stacks/dev || exit 1
        terraform init || exit 1

    - name: Terraform Plan
      run: |
        cd terraform/stacks/dev || exit 1
        terraform plan -out=tfplan || exit 1

    - name: Terraform Apply
      run: |
        cd terraform/stacks/dev || exit 1
        terraform apply -auto-approve tfplan || exit 1

    - name: Cleanup Plan File
      run: |
        cd terraform/stacks/dev || exit 1
        rm tfplan || exit 1

  notify:
    name: Notify on Success
    runs-on: ubuntu-latest
    needs: terraform  # Ensures this job runs only after the terraform job succeeds

    steps:
    - name: Send notification
      run: |
        echo "Terraform deployment successful!"
